Repository Activiti/activiti-api, pull requests merged in 2018-11, with the labels that each got.

#37 fix: add missing processInstanceId in RuntimeEvent api
  activiti-api-model-shared-impl/src/main/java/org/activiti/api/runtime/event/impl/RuntimeEventImpl.java
  activiti-api-model-shared/src/main/java/org/activiti/api/model/shared/event/RuntimeEvent.java
Labels: enhancement, in progress

#42 Create .mergify.yml
  .mergify.yml
Labels: enhancement, in progress

#45 fix: enable single pr into activiti-dependencies
  .updatebot.yml
Labels: enhancement, in progress

#48 update org.activiti.build:activiti-parent to 7.0.40
  pom.xml
Labels: in progress, updatebot

#49 fix: fine-tune mergify rules for pull requests approval
  .mergify.yml
  .updatebot.yml
Labels: in progress

#47 Add process deployed event to the API
  activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/event/impl/ProcessDeployedEventImpl.java
  activiti-api-process-model/src/main/java/org/activiti/api/process/model/events/ProcessDefinitionEvent.java
  activiti-api-process-model/src/main/java/org/activiti/api/process/model/events/ProcessDeployedEvent.java
Labels: in progress

#51 update org.activiti.build:activiti-parent to 7.0.41
  pom.xml
Labels: in progress, ready-to-merge, updatebot

#52 feat: id property is added for BPMNElement
  activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/conf/impl/ProcessModelAutoConfiguration.java
  activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/event/impl/SequenceFlowTakenImpl.java
  activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/model/impl/BPMNActivityImpl.java
  activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/model/impl/BPMNElementImpl.java
  activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/model/impl/BPMNSequenceFlowImpl.java
  activiti-api-process-model/src/main/java/org/activiti/api/process/model/BPMNActivity.java
  activiti-api-process-model/src/main/java/org/activiti/api/process/model/BPMNElement.java
  activiti-api-process-model/src/main/java/org/activiti/api/process/model/BPMNSequenceFlow.java
  activiti-api-process-model/src/main/java/org/activiti/api/process/model/events/SequenceFlowEvent.java
Labels: in progress

#55 fix: (updatebot) push version into activiti-core via single pr
  .updatebot.yml
  activiti-api-dependencies-tests/pom.xml
  activiti-api-dependencies/pom.xml
  activiti-api-model-shared-impl/pom.xml
  activiti-api-model-shared/pom.xml
  activiti-api-process-model-impl/pom.xml
  activiti-api-process-model/pom.xml
  activiti-api-process-runtime/pom.xml
  activiti-api-runtime-shared/pom.xml
  activiti-api-task-model-impl/pom.xml
  activiti-api-task-model/pom.xml
  activiti-api-task-runtime/pom.xml
  pom.xml
Labels: enhancement, in progress

#56 fix(versions): update Activiti/activiti-api versions
  pom.xml
Labels: in progress, updatebot

#57 Update process instance properties via API #2147
  activiti-api-process-model/src/main/java/org/activiti/api/process/model/builders/UpdateProcessPayloadBuilder.java
  activiti-api-process-model/src/main/java/org/activiti/api/process/model/payloads/UpdateProcessPayload.java
Labels: in progress

#58 Automated tests for dependencies convergence in CI pipelines for Activiti Cloud
  .mergify.yml
  activiti-api-dependencies-tests/pom.xml
  activiti-api-dependencies/pom.xml
  pom.xml
Labels: enhancement, in progress

#59 fix(versions): update Activiti/activiti-api versions
  pom.xml
Labels: in progress, updatebot

#60 fix(versions): update Activiti/activiti-api versions
  pom.xml
Labels: in progress, updatebot

#61 fix(versions): update Activiti/activiti-api versions
  pom.xml
Labels: in progress, updatebot
