Repository Activiti/activiti-api, pull requests merged in 2019-11, with the labels that each got.

#152 refactor(AAE-102): polish StartMessageDeploymentDefinitionImpl attribute names
  activiti-api-process-model-impl/src/main/java/org/activiti/api/runtime/model/impl/StartMessageDeploymentDefinitionImpl.java
Labels: enhancement

#153 fix(versions): update Activiti/activiti-api versions into develop
  pom.xml
Labels: updatebot

#154 fix(versions): update Activiti/activiti-api versions into develop
  pom.xml
Labels: updatebot

#155 fix(versions): update Activiti/activiti-api versions into develop
  pom.xml
Labels: updatebot

#126 AAE-771 taskDefinitionKey is added to the Task model
  activiti-api-task-model-impl/src/main/java/org/activiti/api/task/model/impl/TaskImpl.java
  activiti-api-task-model/src/main/java/org/activiti/api/task/model/Task.java
  activiti-api-task-model/src/main/java/org/activiti/api/task/model/builders/CreateTaskPayloadBuilder.java
Labels: ready-for-review
